### ISSUE TITLE
[Suggestion] ability to place down Baskets

### ISSUE THREAD

**Issue by HanatakeYurii** [clumsyc/decoration-mod#3]
This small mod is already fun (even if it could use some expansion such as a shower head) but it would be awesome if we could place Baskets as blocks (maybe right-clicking to take it back).

Anyways good work!

**Comment by clumsyc** [comment]
Im happy to hear that :)
I originally had many plans for this mod, but I have been super busy recently, so I don't have much free time to work on it.

One of the features I had in mind was to make Baskets work like bags, I may also look into making them placeable.
Another was to redo the model for that shower head and "box", making them interactables and completely functional.

Well, hopefully I can manage some spare time to port this mod to the new 1.20 update soon. Maybe even expand it, even if by a little bit.

Thanks for the feedback.

**Comment by HanatakeYurii** [comment]
You're welcome
And while I think about it, the ability to connect walls (and maybe fences) to the clock (especially the sides) and making it full height would allow for impressive designs (clocks could be integrated in thin walls).
