### ISSUE TITLE
TrashCan issue

### ISSUE THREAD

**Issue by freeman401** [clumsyc/decoration-mod#5]
**Furniture Expanded 1.1-1.20.1 Fabric**
There's a conflict with "Macaw's Furniture 3.2.1" mod
![image](https://github.com/clumsyc/decoration-mod/assets/65763306/5db8cf9f-a1c9-4268-9e2c-c6d24d1ffbda)
Sorry, I could only post a screenshot

**Comment by clumsyc** [comment]
As I don't have access to the other mod source code, all I can do is speculate what it is trying to do.

Anyways, I added a check before trying to access the trashcan tile entity, so in theory it should fix the problem. Can you try it out?
[furnitureexpanded-1.1-1.20.1-FABRIC.zip](https://github.com/clumsyc/decoration-mod/files/13851866/furnitureexpanded-1.1-1.20.1-FABRIC.zip)
_Don't forget to unzip it._

**Comment by freeman401** [comment]
Unfortunately, I was unable ro recreate the issue with the older version of the mod to check if the new one actually solves it. But I updated it just in case.
I will post here if the problem happens again in the future.
Thank you!

**Comment by clumsyc** [comment]
Thank you for letting me know about it.
I'm glad that this is not a recurring problem, so i'll postpone this _hopefully_ "fix" for the next release.  

For now, I'll be marking this as solved.
